### ISSUE TITLE
ImportError: cannot import name Counter from Crypto.util

### ISSUE THREAD

**Issue by sree0410** [tgalal/yowsup#1632]
Hi 
i am trying to send a message through yowsup-cli 

./yowsup-cli demos -y -l <loginNum:Passowrd>

i get the error stack as

 File "./yowsup-cli", line 368, in <module>
    if not parser.process():
  File "./yowsup-cli", line 268, in process
    self.startCmdline()
  File "./yowsup-cli", line 290, in startCmdline
    from yowsup.demos import cli
  File "/home/rpy/yowsup-master/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/home/rpy/yowsup-master/yowsup/demos/cli/stack.py", line 5, in <module>
    from yowsup.layers.axolotl.props import PROP_IDENTITY_AUTOTRUST
  File "/home/rpy/yowsup-master/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer_send import AxolotlSendLayer
  File "/home/rpy/yowsup-master/yowsup/layers/axolotl/layer_send.py", line 6, in <module>
    from axolotl.sessioncipher import SessionCipher
  File "/usr/local/lib/python2.6/dist-packages/python_axolotl-0.1.35-py2.6.egg/axolotl/sessioncipher.py", line 6, in <module>
    from Crypto.Util import Counter
ImportError: cannot import name Counter

i am using python 2.6
is there any package which i have to install, i have installed pycrypto from this below site

wget https://pypi.python.org/packages/source/p/pycrypto/pycrypto-2.6.1.tar.gz#md5=55a61a054aa66812daf5161a0d5d7eda

so after installing i see the below stack 

running install
running build
running build_py
running build_ext
running build_configure
running install_lib
running install_egg_info
Removing /usr/local/lib/python2.6/dist-packages/pycrypto-2.6.1.egg-info
Writing /usr/local/lib/python2.6/dist-packages/pycrypto-2.6.1.egg-info

which means it installed successfully write ?

Is there anything i am missing here 
please help me
Thanks In Advance

**Comment by mp3il** [comment]
what about pip install Crypto ?

**Comment by sree0410** [comment]
Hi ,
This work s now 
pip install crypto , it works in python2.6 

Thanks 

but i face a different problem now 

when i do ./yowsup-clli demos -y -l <login:Password>

i get the status as 

Error: Not connected
[offline]:/L
general: Disconnected: Connection Closed


how do i authenticate the login details what i have obtained during registration

**Comment by sree0410** [comment]
closing the issue as actual problem is solved
