### ISSUE TITLE
Yowsup 2 does not work with Python 2.6

### ISSUE THREAD

**Issue by jakofff** [tgalal/yowsup#549]
In Python 2.6 when you run the login generates the following error:

yowsup-cli demos --yowsup --login phone:b64password

from Crypto.Util import Counter
ImportError: cannot import name Counter

Counter works only with Python 2.7

**Comment by tgalal** [comment]
on it

**Comment by tgalal** [comment]
working fine with me on python2.6.8

**Comment by gentunian** [comment]
Hi @tgalal 

I'm having the same issue running `yowsup-cli`. Does `Crypto.Util` come with a default Python installation or do I need to install something? I have `python-crypto` installed:

```
Package python-crypto-2.0.1-22.el6.x86_64 already installed and latest version
Nothing to do
~# python -V
Python 2.6.6
```

cheers

**Comment by kzeta** [comment]
hi all

have the same problem, i tried this and it works

download pycrypto 2.6.1

wget https://pypi.python.org/packages/source/p/pycrypto/pycrypto-2.6.1.tar.gz#md5=55a61a054aa66812daf5161a0d5d7eda

tar archive
install from folder
#python setup.py install

then run yowsup-client demos --yowsup --login phone:pass and works

Yowsup Cli client
==================
Type /help for available commands

[offline]:


hope it helps.

cheers
KaZeta

**Comment by sree0410** [comment]
Hi After installing it i still face the issue 

 File "./yowsup-cli", line 368, in <module>
    if not parser.process():
  File "./yowsup-cli", line 268, in process
    self.startCmdline()
  File "./yowsup-cli", line 290, in startCmdline
    from yowsup.demos import cli
  File "/home/rpy/yowsup-master/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/home/rpy/yowsup-master/yowsup/demos/cli/stack.py", line 5, in <module>
    from yowsup.layers.axolotl.props import PROP_IDENTITY_AUTOTRUST
  File "/home/rpy/yowsup-master/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer_send import AxolotlSendLayer
  File "/home/rpy/yowsup-master/yowsup/layers/axolotl/layer_send.py", line 6, in <module>
    from axolotl.sessioncipher import SessionCipher
  File "/usr/local/lib/python2.6/dist-packages/python_axolotl-0.1.35-py2.6.egg/axolotl/sessioncipher.py", line 6, in <module>
    from Crypto.Util import Counter
ImportError: cannot import name Counter


please help me.

**Comment by sree0410** [comment]
after upgrading to python 2.7  we have to install all the supporting packages right like setuptools ncurse-dev  and then we have to clone the yowsup files as well .

do we have to register again to whatsapp  ? registerd login credentials will suffice ?

and  this particular watsapp registered number is only for this particulat system right ?this credentials can be used in different linux machine ?

how do we cross verify the login and password which is obtained is active or not ?
Thanks,
sreelekha.N
