### ISSUE TITLE
Issue with installing

### ISSUE THREAD

**Issue by Rex90** [tgalal/yowsup#800]
Hi I get the following error when trying to install yowsup on windows... any help is appreciated

python setup.py install

Processing dependencies for yowsup2==2.2.78
Searching for python-axolotl-curve25519
Reading https://pypi.python.org/simple/python-axolotl-curve25519/
Best match: python-axolotl-curve25519 0.1
Downloading https://pypi.python.org/packages/source/p/python-axolotl-curve25519/
python-axolotl-curve25519-0.1.tar.gz#md5=f28d902df9044f0bf86a35a4bd2ec092
Processing python-axolotl-curve25519-0.1.tar.gz
Writing c:\users\appdata\local\temp\easy_install-raecqz\python-axolotl-c
urve25519-0.1\setup.cfg
Running python-axolotl-curve25519-0.1\setup.py -q bdist_egg --dist-dir c:\users\\appdata\local\temp\easy_install-raecqz\python-axolotl-curve25519-0.1\egg
-dist-tmp-bkci3l
curve25519module.c
curve25519module.c(76) : error C2143: syntax error : missing ';' before 'type'
curve25519module.c(78) : error C2065: 'result' : undeclared identifier
curve25519module.c(82) : error C2143: syntax error : missing '{' before '*'
curve25519module.c(100) : warning C4133: 'return' : incompatible types - from 'P
yObject *' to 'int *'
curve25519module.c(146) : warning C4133: 'initializing' : incompatible types - f
rom 'int *(__cdecl *)(PyObject *,PyObject *)' to 'PyCFunction'
error: Setup script exited with error: command 'C:\Users\AppData\Loc
al\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe' fa
iled with exit status 2
##

**Comment by LMS0815** [comment]
same problem

**Comment by Dl0tt** [comment]
try

sudo python setup.py install

**Comment by AnshulLearning** [comment]
i am facing the same issue ... was anybody able to get rid of this issue?

**Comment by tgalal** [comment]
Was this with the [windows installation instructions](https://github.com/tgalal/yowsup#windows)?

**Comment by AnshulPytho** [comment]
yes , tgalal. Even i am facing the same issue.
Anybody know how to sort it out ?

**Comment by eduardobento** [comment]
Same problem... Windows instalation with Python 2.7!

**Comment by srinarasi** [comment]
I have the same problem. Win 10, Python 2.7.10 and have VCForPython27 installed.

**Comment by antonio9213** [comment]
@armensg @LMS0815 @AnshulLearning @eduardobento @srinarasi 
That is a problem caused by MS C compiler not supporting C99. Source code of one of yowsup's dependences (python-axolotl-curve25519), uses variable definitions mixed with code, a feature introduced in C99. To get rid of this problem without modifying that module's code, I will tell you what worked for me:

1. Install **Python 2.7.9** for Windows x32. I do not know if it works with Python 3 or the x64 versions, just know that it works well with 2.7.9 and that it does NOT work with 2.7.10.

2. Download and install **MinGW** from http://sourceforge.net/projects/mingw/files/ (Select Installer, download the mingw-get setup package and follow instructions to install MinGW with MSYS and C compiler). We need it as the gcc included with MinGW supports C99.

3. Navigate to `C:\Python27\Lib\distutils` (providing you installed Python in `C:\Python27`) and create a plain text file called `distutils.cfg` with the following content (two lines):

`[build]`
`compiler=mingw32`

4. Download **zlib for MinGW32** from http://sourceforge.net/projects/mingw/files/MinGW/Extension/zlib/zlib-1.2.7-1/ (pick the dev version) and copy the files to *include* and *lib* directories in your MinGW installation.

5. Now go to your **yowsup** folder and attempt `python setup.py install` again, it should complete without problems.

**Comment by Deepankar01** [comment]
@armensg @LMS0815 @AnshulLearning @eduardobento @srinarasi  and thanks to @antonio9213 for letting us know 

- tried with 2.7.10-x64 doesn't work both on vc and minGW
- tried with 2.7.10-x86 doesn't work both on vc and minGW
- tried with 2.7.9-x64 doesn't work both on vc and minGW 

> all the above had the same issue with *python-axolotl-curve25519* compilation
 
**tried with 2.7.9-x86 it worked with minGW**
had chmod issue did what was said in **readme** library is working fine

**Comment by gullyy** [comment]
getting the same problem..tried the solution posted by @antonio9213  not working. using windows 8.1 64 bit. Any other lead?

**Comment by Deepankar01** [comment]
@gully do with python 2.7.9 x86 version it is working for me it worked for me in 10 i think it should work in 8.1

**Comment by gullyy** [comment]
@Deepankar01  Thanks it worked

**Comment by akeskimo** [comment]
This worked great! Thank you for great post, Antonio!

**Comment by erezak** [comment]
It should work well with 2.7.11
But for me it only worked with it when I put the configuration in c:\users\<my>\pydistutils.cfg

**Comment by jlguardi** [comment]
Mensajeoriginal

De: Erez A. Korn
Enviado: miércoles, 1 de junio de 2016 16:44
Para: tgalal/yowsup
Responder a: tgalal/yowsup
Asunto: Re: [tgalal/yowsup] Issue with installing (#800)



It should work well with 2.7.11
But for me it only worked with it when I put the configuration in c:\users<my>\pydistutils.cfg

-

**Comment by gullyy** [comment]
For those who are stuck in the chmod error can use this link.It worked for me.
http://stackoverflow.com/questions/11405549/how-do-i-install-pycrypto-on-windows

**Comment by tusharsingh8** [comment]
@antonio9213 where is the yowsup folder supposed to be?
I go to the one in site-packages and get the error python is not recognized as an internal or external command. 
I am installing it on windows. Where did I go wrong?

**Comment by dickbutt2** [comment]
guys i'm having the same error

2.7
2.7.9 64
2.7.9 86

all not working :/

**Comment by biboff** [comment]
Is there anybody getting this Issue concerning _python-axolotl-curve25519_ on a Raspberry Pi using Raspbian GNU/Linux 9 (stretch) on Kernel Linux 4.9.35-v7+ armv7l and Python 2.7.13 ?
