### ISSUE TITLE
Yowsup 2 does not work with Python 2.6

### ISSUE THREAD

**Issue by joschi99** [tgalal/yowsup#681]
In Python 2.6.6 / Centos 6.6 when you run the login generates the following error:

yowsup-cli demos -d -c /etc/yowsup2/config -m -y
Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 304, in <module>
    if not parser.process():
  File "/usr/bin/yowsup-cli", line 223, in process
    self.startCmdline()
  File "/usr/bin/yowsup-cli", line 243, in startCmdline
    from yowsup.demos import cli
  File "/usr/lib/python2.6/site-packages/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/usr/lib/python2.6/site-packages/yowsup/demos/cli/stack.py", line 1, in <module>
    from yowsup.stacks import YowStack, YowStackBuilder
  File "/usr/lib/python2.6/site-packages/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/usr/lib/python2.6/site-packages/yowsup/stacks/yowstack.py", line 21, in <module>
    from yowsup.layers.axolotl import YowAxolotlLayer
  File "/usr/lib/python2.6/site-packages/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/usr/lib/python2.6/site-packages/yowsup/layers/axolotl/layer.py", line 14, in <module>
    from axolotl.sessioncipher import SessionCipher
  File "/usr/lib/python2.6/site-packages/axolotl/sessioncipher.py", line 3, in <module>
    from Crypto.Util import Counter
ImportError: cannot import name Counter

It seems the same issue described on #549
