### ISSUE TITLE
Not able to log in

### ISSUE THREAD

**Issue by NicoSoftware** [tgalal/yowsup#2739]
when logging in with "/L" in the yowsup-cli I get the following error:
```
[offline]:/L
I 2019-05-10 19:19:59,631 yowsup.layers.network.layer - Connecting to e1.whatsapp.net:443
I 2019-05-10 19:19:59,761 yowsup.axolotl.manager - Generating 812 prekeys
E 2019-05-10 19:19:59,773 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/local/lib/python3.6/asyncore.py", line 441, in handle_write_event
    self.handle_connect_event()
  File "/usr/local/lib/python3.6/asyncore.py", line 429, in handle_connect_event
    self.handle_connect()
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/network/layer.py", line 53, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/axolotl/layer_control.py", line 46, in on_connected
    self.manager.level_prekeys()
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/axolotl/manager.py", line 69, in level_prekeys
    prekeys = KeyHelper.generatePreKeys(KeyHelper.getRandomSequence(), count_gen)
TypeError: getRandomSequence() missing 1 required positional argument: 'max'
```
Any Ideas how to fix this? 
- Working on a Raspberry Pi with a Raspbian installation.
installed all dependencies and was working with python3.6
Thanks!

**Comment by tgalal** [comment]
update to yowsup 3.2.3
