### ISSUE TITLE
After Login /L i am getting error and how to send message to group 

### ISSUE THREAD

**Issue by prabhakaran2304** [tgalal/yowsup#2514]
**after login cli console i am facing below error , please help me out .**
Auth: Logged in!
[connected]:Notification: Notification
From: xxxxx-xxxxxxxx@g.us
Type: w:gp2
Participant: xxxxxxx@s.whatsapp.net
Creator: xxxxxxxx@s.whatsapp.net
Create type: None
Creation timestamp: xxxxxx
Subject: xxxxx
Subject owner: xxxxxxxxxx@s.whatsapp.net
Subject timestamp: xxxxxxxxxx
Participants: {'xxxxx@s.whatsapp.net': None, 'xxxxx@s.whatsapp.net': None, 'xxxxxxxx@s.whatsapp.net': None, 'xxxxx@s.whatsapp.net': None, 'xxxxxx@s.whatsapp.net': 'admin', 'xxxxxxx@s.whatsapp.net': None}

[connected]:

Traceback (most recent call last):
  File "./yowsup-cli", line 368, in <module>
    if not parser.process():
  File "./yowsup-cli", line 268, in process
    self.startCmdline()
  File "./yowsup-cli", line 297, in startCmdline
    stack.start()
  File "/home/yowsup/yowsup/demos/cli/stack.py", line 26, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/home/yowsup/yowsup/stacks/yowstack.py", line 189, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/yowsup/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/home/yowsup/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/home/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/yowsup/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/home/yowsup/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/home/yowsup/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/home/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/yowsup/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/home/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/yowsup/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/yowsup/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/home/yowsup/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    entity = TextMessageProtocolEntity.fromProtocolTreeNode(node)
  File "/home/yowsup/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'

**Comment by iamjagjeetubhi** [comment]
Hey just install these packeges:

`sudo apt-get install build-essential autoconf libtool pkg-config python-pyrex idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script libqt4-network libqt4-dbus python-dev libssl-dev libffi6 libffi-dev
`

than apply the following commands in your YOWSUP directory:

`sudo python setup.py build
`
`sudo python setup.py install
`

Now again login and I hope it will fix your problem.

**Comment by prabhakaran2304** [comment]
hi , still same error is coming .

**Comment by prabhakaran2304** [comment]
Now , its working in ubuntu 18.04 server setup after updating all packages .

**Comment by wz343450860** [comment]
Hi, 
   could you tell me how can you login in ,  when I get the base64password, but I can not login in, if I run the command 'yowsup-cli demos -e -M -E android -l phonenum:password -d' it always return 
'''DEBUG:yowsup.layers.logger.layer:rx:
<failure location="wdc">
<not-authorized>
</not-authorized>
</failure>
'''

**Comment by wz343450860** [comment]
Hi,
could you tell me how can you login in , when I get the base64password, but I can not login in, if I run the command 'yowsup-cli demos -e -M -E android -l phonenum:password -d' it always return
'''<failure location="wdc">
<not-authorized>
</not-authorized>
</failure>'''

**Comment by wz343450860** [comment]
Hi, 
   could you tell me how to login, I get the password but I can not to login , when I execute the command 'yowsup-cli demos -e -M -E android -l phonenum:password -d'  it always return not-authorized
