### ISSUE TITLE
cannot send message

### ISSUE THREAD

**Issue by hasan** [tgalal/yowsup#2725]
Hello,

i'm trying to send a message with yowsup but, i get an error
Versions
> yowsup-cli  v3.2.0
> yowsup      v3.2.0
> python 3.6

Error 

```
vagrant@homestead:~/code/Personal/utils/yowsup$ ./yowsup-cli demos --config ~/.config/yowsup/79xxxxxx/config.json -s 90xxxxxx test
yowsup-cli  v3.2.0
yowsup      v3.2.0

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


I 2019-05-07 08:32:08,835 yowsup.layers.network.layer - Connecting to e8.whatsapp.net:443
I 2019-05-07 08:32:09,063 yowsup.axolotl.manager - Generating 812 prekeys
E 2019-05-07 08:32:09,077 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python3.6/asyncore.py", line 441, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python3.6/asyncore.py", line 429, in handle_connect_event
    self.handle_connect()
  File "/home/vagrant/code/Personal/utils/yowsup/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/home/vagrant/code/Personal/utils/yowsup/yowsup/layers/network/layer.py", line 53, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/home/vagrant/code/Personal/utils/yowsup/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/vagrant/code/Personal/utils/yowsup/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/vagrant/code/Personal/utils/yowsup/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/home/vagrant/code/Personal/utils/yowsup/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/home/vagrant/code/Personal/utils/yowsup/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/home/vagrant/code/Personal/utils/yowsup/yowsup/layers/axolotl/layer_control.py", line 57, in on_connected
    self.manager.level_prekeys()
  File "/home/vagrant/code/Personal/utils/yowsup/yowsup/axolotl/manager.py", line 69, in level_prekeys
    prekeys = KeyHelper.generatePreKeys(KeyHelper.getRandomSequence(), count_gen)
TypeError: getRandomSequence() missing 1 required positional argument: 'max'
```

**Comment by tgalal** [comment]
update to latest master or use a released version

**Comment by hasan** [comment]
i tried v3.1.0 release but i get same error.


```
(yowsup-test) vagrant@homestead:/opt/yowsup-test/yowsup$ yowsup-cli demos --config ~/.config/yowsup/79xxxxxx/config.json --send 90xxxxxxx deneme
yowsup-cli  v3.0.0
yowsup      v3.1.0

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


I 2019-05-07 09:32:11,846 yowsup.layers.network.layer - Connecting to e15.whatsapp.net:443
I 2019-05-07 09:32:12,042 yowsup.axolotl.manager - Generating 812 prekeys
E 2019-05-07 09:32:12,044 yowsup.layers.network.dispatcher.dispatcher_socket - getRandomSequence() missing 1 required positional argument: 'max'
```

**Comment by tgalal** [comment]
I've just published version 3.2.1, can you try and close the issue if it's fixed?

**Comment by NelsonGaldeman** [comment]
I was trying to send a message with 3.1.0 but it keeps showing an error
`yowsup.layers.network.dispatcher.dispatcher_socket - getRandomSequence() takes exactly 1 argument (0 given)
`

After updating to 3.2.3, the error changed:

	yowsup-cli  v3.2.0
	yowsup      v3.2.3

	Copyright (c) 2012-2019 Tarek Galal
	http://www.openwhatsapp.org

	This software is provided free of charge. Copying and redistribution is
	encouraged.

	If you appreciate this software and you would like to support future
	development please consider donating:
	http://openwhatsapp.org/yowsup/donate


	I 2019-05-17 18:25:09,734 yowsup.layers.network.layer - Connecting to e16.whatsapp.net:443
	I 2019-05-17 18:25:10,019 yowsup.axolotl.manager - Generating 812 prekeys
	I 2019-05-17 18:25:10,552 yowsup.axolotl.manager - Storing 812 prekeys
	I 2019-05-17 18:25:16,302 yowsup.axolotl.manager - Loaded 812 unsent prekeys
	E 2019-05-17 18:25:18,556 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
	  File "C:\python27\lib\asyncore.py", line 83, in read
		obj.handle_read_event()
	  File "C:\python27\lib\asyncore.py", line 449, in handle_read_event
		self.handle_read()
	  File "C:\yowsup-3.2.3\yowsup\layers\network\dispatcher\dispatcher_asyncore.py", line 48, in handle_read
		self.connectionCallbacks.onRecvData(data)
	  File "C:\yowsup-3.2.3\yowsup\layers\network\layer.py", line 100, in onRecvData
		self.receive(data)
	  File "C:\yowsup-3.2.3\yowsup\layers\network\layer.py", line 103, in receive
		self.toUpper(data)
	  File "C:\yowsup-3.2.3\yowsup\layers\__init__.py", line 79, in toUpper
		self.__upper.receive(data)
	  File "C:\yowsup-3.2.3\yowsup\layers\noise\layer_noise_segments.py", line 39, in receive
		self.toUpper(bytes(data))
	  File "C:\yowsup-3.2.3\yowsup\layers\__init__.py", line 79, in toUpper
		self.__upper.receive(data)
	  File "C:\yowsup-3.2.3\yowsup\layers\noise\layer.py", line 156, in receive
		self._flush_incoming_buffer()
	  File "C:\yowsup-3.2.3\yowsup\layers\noise\layer.py", line 144, in _flush_incoming_buffer
		self.toUpper(self._wa_noiseprotocol.receive())
	  File "C:\yowsup-3.2.3\yowsup\layers\__init__.py", line 79, in toUpper
		self.__upper.receive(data)
	  File "C:\yowsup-3.2.3\yowsup\layers\coder\layer.py", line 21, in receive
		self.toUpper(node)
	  File "C:\yowsup-3.2.3\yowsup\layers\__init__.py", line 79, in toUpper
		self.__upper.receive(data)
	  File "C:\yowsup-3.2.3\yowsup\layers\logger\layer.py", line 14, in receive
		self.toUpper(data)
	  File "C:\yowsup-3.2.3\yowsup\layers\__init__.py", line 79, in toUpper
		self.__upper.receive(data)
	  File "C:\yowsup-3.2.3\yowsup\layers\axolotl\layer_control.py", line 28, in receive
		if not self.processIqRegistry(protocolTreeNode):
	  File "C:\yowsup-3.2.3\yowsup\layers\__init__.py", line 163, in processIqRegistry
		errorClbk(protocolTreeNode, originalIq)
	  File "C:\yowsup-3.2.3\yowsup\layers\axolotl\layer_control.py", line 118, in onSentKeysError
		raise Exception("Sent keys were not accepted")
	Exception: Sent keys were not accepted

Command sent:

    yowsup-cli demos -E android -s 549XXXXXXXXXX prueba --config-phone 549XXXXXXXXXXX --config-pushname prueba --config-expid XXXXXXXXXXXXX --config-cc 54 --config-client_static_keypair XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --config-id XXXXXXXXXxx --config-fdid XXXXXXXXXXXXXXXXXXXXXX

**Comment by NicoSoftware** [comment]
> 	raise Exception("Sent keys were not accepted")
> Exception: Sent keys were not accepted

I got the same exception, did you find a solution?

**Comment by tgalal** [comment]
how about we all stop hijacking issues with irrelevant stuff
